from app.deployment.env_detector import detect_env_vars, find_missing, write_env_example


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def test_detects_dot_bracket_and_destructured_access(tmp_path):
    write(tmp_path / "src/a.ts", "const k = process.env.STRIPE_KEY;")
    write(tmp_path / "src/b.js", 'const u = process.env["DATABASE_URL"];')
    write(tmp_path / "src/c.tsx", "const { API_TOKEN, SMTP_HOST: host, PORT_X = 3 } = process.env;")
    assert detect_env_vars(tmp_path) == {
        "STRIPE_KEY", "DATABASE_URL", "API_TOKEN", "SMTP_HOST", "PORT_X",
    }


def test_ignores_node_modules_next_and_non_source_files(tmp_path):
    write(tmp_path / "node_modules/lib/index.js", "process.env.FROM_NODE_MODULES")
    write(tmp_path / ".next/server/page.js", "process.env.FROM_NEXT_BUILD")
    write(tmp_path / "README.md", "process.env.FROM_README")
    write(tmp_path / "app/page.tsx", "process.env.REAL_ONE")
    assert detect_env_vars(tmp_path) == {"REAL_ONE"}


def test_ignores_platform_builtins(tmp_path):
    write(tmp_path / "a.js", "process.env.NODE_ENV; process.env.VERCEL_URL; process.env.MY_VAR")
    assert detect_env_vars(tmp_path) == {"MY_VAR"}


def test_find_missing():
    assert find_missing({"A", "B", "C"}, ["B"]) == ["A", "C"]


def test_write_env_example_creates_names_only_file(tmp_path):
    added = write_env_example(tmp_path, {"B_VAR", "A_VAR"})
    text = (tmp_path / ".env.example").read_text()
    assert added == ["A_VAR", "B_VAR"]
    assert "A_VAR=\n" in text and "B_VAR=\n" in text
    assert text.startswith("# Generated by TeslaLab")


def test_write_env_example_never_reads_real_env_values(tmp_path):
    write(tmp_path / ".env", "STRIPE_KEY=sk_live_REAL_SECRET\n")
    write_env_example(tmp_path, {"STRIPE_KEY"})
    assert "sk_live_REAL_SECRET" not in (tmp_path / ".env.example").read_text()


def test_write_env_example_merges_and_preserves_existing(tmp_path):
    write(tmp_path / ".env.example", "# my notes\nEXISTING=default-ok")
    added = write_env_example(tmp_path, {"EXISTING", "NEW_VAR"})
    text = (tmp_path / ".env.example").read_text()
    assert added == ["NEW_VAR"]
    assert "# my notes" in text and "EXISTING=default-ok" in text
    assert text.count("EXISTING") == 1
    assert "NEW_VAR=\n" in text


def test_destructured_names_with_whitespace_are_clean(tmp_path):
    write(tmp_path / "a.ts", "const {\n  FIRST_VAR,\n  SECOND_VAR\n} = process.env;")
    assert detect_env_vars(tmp_path) == {"FIRST_VAR", "SECOND_VAR"}
