"""
Formal Plan Schema for Engineer 2 (Agent 2).

Provides models for:
- ExecutionPlan
- PlanStep
- StepOutcome
"""

from __future__ import annotations
from typing import Any, Literal
from pydantic import BaseModel, ConfigDict, Field, field_validator


ALLOWED_TOOLS = {
    "read_file",
    "search_code",
    "apply_patch",
    "run_tests",
    "run_command",
    "open_pr",
}

AllowedToolName = Literal[
    "read_file",
    "search_code",
    "apply_patch",
    "run_tests",
    "run_command",
    "open_pr",
]


class PlanStep(BaseModel):
    model_config = ConfigDict(extra="forbid")

    step_number: int = Field(..., ge=1, description="1-indexed sequence number of the step")
    tool_name: AllowedToolName = Field(..., description="Name of the tool to execute")
    tool_arguments: Any = Field(
        ...,
        description="Tool arguments matching the tool schema",
    )
    expected_outcome: str = Field(..., min_length=1, description="Expected result or condition after execution")
    rollback_action: str = Field(..., min_length=1, description="Action or command to revert this step on failure")

    @field_validator("tool_name")
    @classmethod
    def validate_tool_name(cls, v: str) -> str:
        if v not in ALLOWED_TOOLS:
            allowed_str = ", ".join(sorted(ALLOWED_TOOLS))
            raise ValueError(f"Unknown tool '{v}'. Allowed tools are: {allowed_str}")
        return v


class ExecutionPlan(BaseModel):
    model_config = ConfigDict(extra="forbid")

    goal: str = Field(..., min_length=1, description="Primary goal and description of what the plan accomplishes")
    steps: list[PlanStep] = Field(..., min_length=1, description="Ordered list of execution steps")
    affected_files: list[str] = Field(default_factory=list, description="List of file paths targeted by the plan")
    estimated_complexity: str = Field(..., min_length=1, description="Complexity assessment (e.g. Low, Medium, High)")
    rollback_plan: str = Field(..., min_length=1, description="Overall rollback instructions if execution aborts")

    @field_validator("affected_files")
    @classmethod
    def normalize_affected_files(cls, files: list[str]) -> list[str]:
        cleaned: list[str] = []
        for f in files:
            norm = f.strip().replace("\\", "/")
            if norm and norm not in cleaned:
                cleaned.append(norm)
        return cleaned


class StepOutcome(BaseModel):
    model_config = ConfigDict(extra="forbid")

    step_number: int = Field(..., ge=1, description="Step sequence number")
    tool_name: AllowedToolName = Field(..., description="Tool that was executed")
    success: bool = Field(..., description="Whether the step completed successfully")
    output: str | None = Field(default=None, description="Standard output or result payload")
    error: str | None = Field(default=None, description="Error message if step failed")
    artifacts: dict[str, Any] = Field(default_factory=dict, description="Artifacts or outputs generated by the step")
