"""Detect environment variables used by a project and generate .env.example.

- Scans source files for process.env.X, process.env["X"] and
  const { X, Y } = process.env.
- Writes NAMES only. It never reads .env files, so real values cannot leak
  into .env.example.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Iterable

_NAME = r"[A-Za-z_][A-Za-z0-9_]*"
_DOT = re.compile(rf"process\.env\.({_NAME})")
_BRACKET = re.compile(rf"""process\.env\[\s*['"]({_NAME})['"]\s*\]""")
_DESTRUCTURE = re.compile(r"\{([^{}]*)\}\s*=\s*process\.env\b")
_NAME_ONLY = re.compile(rf"^{_NAME}$")

SOURCE_EXTENSIONS = {".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"}
IGNORED_DIRS = {"node_modules", ".next", ".git", ".vercel", "dist", "build", "out", "coverage"}
MAX_FILE_BYTES = 1_000_000

# Provided by the platform / framework, so they are not "missing" variables.
BUILTIN_NAMES = {"NODE_ENV", "NEXT_RUNTIME", "CI", "PORT"}
BUILTIN_PREFIXES = ("VERCEL_",)

HEADER = (
    "# Generated by TeslaLab. Variable NAMES only.\n"
    "# Never put real secrets in this file; it is committed to git.\n"
)


def _is_builtin(name: str) -> bool:
    return name in BUILTIN_NAMES or name.startswith(BUILTIN_PREFIXES)


def _names_from_text(text: str) -> set[str]:
    found = set(_DOT.findall(text)) | set(_BRACKET.findall(text))
    for group in _DESTRUCTURE.findall(text):
        for part in group.split(","):
            name = part.split(":")[0].split("=")[0].strip()
            if _NAME_ONLY.match(name):  # skips "...rest" and empty parts
                found.add(name)
    return found


def detect_env_vars(project_dir: str | Path) -> set[str]:
    """Return the set of env var names the project's source code reads."""
    found: set[str] = set()
    for root, dirs, files in os.walk(project_dir):
        dirs[:] = [d for d in dirs if d not in IGNORED_DIRS]
        for filename in files:
            path = Path(root) / filename
            if path.suffix not in SOURCE_EXTENSIONS:
                continue
            try:
                if path.stat().st_size > MAX_FILE_BYTES:
                    continue
                found |= _names_from_text(path.read_text(encoding="utf-8", errors="ignore"))
            except OSError:
                continue
    return {n for n in found if not _is_builtin(n)}


def find_missing(detected: Iterable[str], provided: Iterable[str]) -> list[str]:
    """Names the code needs that have not been provided (for deploy warnings)."""
    return sorted(set(detected) - set(provided))


def write_env_example(project_dir: str | Path, names: Iterable[str]) -> list[str]:
    """Create or update .env.example with empty values.

    Existing lines are preserved. Returns the names that were added.
    """
    path = Path(project_dir) / ".env.example"
    existing_text = path.read_text(encoding="utf-8") if path.exists() else ""
    existing_keys = {
        line.split("=", 1)[0].strip()
        for line in existing_text.splitlines()
        if "=" in line and not line.lstrip().startswith("#")
    }
    to_add = sorted(set(names) - existing_keys)

    if not path.exists():
        path.write_text(HEADER + "".join(f"{n}=\n" for n in to_add), encoding="utf-8")
    elif to_add:
        prefix = "" if existing_text.endswith("\n") or not existing_text else "\n"
        with path.open("a", encoding="utf-8") as f:
            f.write(prefix + "".join(f"{n}=\n" for n in to_add))
    return to_add