"""
Purpose:
Starts GitHub App installation for an authenticated TeslaLab workspace.

Responsibilities:
- Authenticate the caller from a Supabase access token.
- Resolve workspace membership on the server (ignore any client workspace id).
- Issue a short-lived HMAC-signed state bound to user and workspace.
- Redirect to the configured GitHub App installation URL.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import time
from json import JSONDecodeError
from urllib.error import HTTPError, URLError
from urllib.parse import quote, urlencode
from urllib.request import Request, urlopen

from fastapi import APIRouter, Header, HTTPException
from fastapi.responses import RedirectResponse

from app.config import (
    frontend_url,
    github_app_slug,
    state_secret,
    supabase_publishable_key,
    supabase_service_role_key,
    supabase_url,
)

STATE_TTL_SECONDS = 600

router = APIRouter()


def _b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def sign_install_state(*, user_id: str, workspace_id: str, secret: str) -> str:
    payload = json.dumps(
        {
            "uid": user_id,
            "wid": workspace_id,
            "exp": int(time.time()) + STATE_TTL_SECONDS,
        },
        separators=(",", ":"),
    ).encode("utf-8")
    body = _b64url(payload)
    signature = hmac.new(secret.encode("utf-8"), body.encode("ascii"), hashlib.sha256).hexdigest()
    return f"{body}.{signature}"


def _json_get(url: str, headers: dict[str, str]) -> tuple[int, object | None]:
    request = Request(url, headers=headers, method="GET")
    try:
        with urlopen(request, timeout=10) as response:
            return response.status, json.loads(response.read().decode("utf-8"))
    except HTTPError as error:
        return error.code, None
    except (URLError, JSONDecodeError, TimeoutError):
        return 503, None


def _json_post(url: str, headers: dict[str, str], data: dict) -> tuple[int, object | None]:
    # Added to make POST requests to the Supabase REST API (e.g. inserting the GitHub installation record)
    payload = json.dumps(data).encode("utf-8")
    request = Request(url, data=payload, headers=headers, method="POST")
    try:
        with urlopen(request, timeout=10) as response:
            return response.status, json.loads(response.read().decode("utf-8") or "{}")
    except HTTPError as error:
        return error.code, None
    except (URLError, JSONDecodeError, TimeoutError):
        return 503, None


def verify_install_state(state: str, secret: str) -> dict:
    # Added to verify the HMAC signature of the state parameter returned by GitHub.
    # This prevents CSRF attacks and ensures the state was originally generated by our backend.
    try:
        body_b64, signature = state.split(".", 1)
        expected_sig = hmac.new(secret.encode("utf-8"), body_b64.encode("ascii"), hashlib.sha256).hexdigest()
        if not hmac.compare_digest(expected_sig, signature):
            raise ValueError("Invalid signature")
        
        padding = 4 - (len(body_b64) % 4)
        if padding != 4:
            body_b64 += "=" * padding
            
        payload = base64.urlsafe_b64decode(body_b64).decode("utf-8")
        data = json.loads(payload)
        
        if data.get("exp", 0) < int(time.time()):
            raise ValueError("State expired")
            
        return data
    except Exception as e:
        raise HTTPException(status_code=400, detail="Invalid state parameter") from e


def _authenticated_user_id(access_token: str) -> str:
    status, body = _json_get(
        f"{supabase_url()}/auth/v1/user",
        {
            "Authorization": f"Bearer {access_token}",
            "apikey": supabase_publishable_key(),
        },
    )
    if status != 200 or not isinstance(body, dict) or not body.get("id"):
        raise HTTPException(status_code=401, detail="Authentication required")
    return str(body["id"])


def _workspace_id_for_user(access_token: str) -> str:
    query = urlencode({"select": "workspace_id", "order": "created_at.asc", "limit": "1"})
    status, body = _json_get(
        f"{supabase_url()}/rest/v1/workspace_members?{query}",
        {
            "Authorization": f"Bearer {access_token}",
            "apikey": supabase_publishable_key(),
        },
    )
    if status == 401:
        raise HTTPException(status_code=401, detail="Authentication required")
    if status != 200 or not isinstance(body, list) or not body:
        raise HTTPException(status_code=400, detail="No workspace found")
    workspace_id = body[0].get("workspace_id")
    if not workspace_id:
        raise HTTPException(status_code=400, detail="No workspace found")
    return str(workspace_id)


@router.post("/api/github/install/start")
def start_github_install(authorization: str | None = Header(default=None)) -> RedirectResponse:
    if not authorization or not authorization.lower().startswith("bearer "):
        raise HTTPException(status_code=401, detail="Authentication required")

    access_token = authorization.split(" ", 1)[1].strip()
    if not access_token:
        raise HTTPException(status_code=401, detail="Authentication required")

    try:
        secret = state_secret()
        app_slug = github_app_slug()
    except RuntimeError as error:
        raise HTTPException(status_code=500, detail="Server configuration is incomplete") from error

    user_id = _authenticated_user_id(access_token)
    workspace_id = _workspace_id_for_user(access_token)
    state = sign_install_state(user_id=user_id, workspace_id=workspace_id, secret=secret)

    install_url = (
        f"https://github.com/apps/{quote(app_slug, safe='')}/installations/new"
        f"?state={quote(state, safe='')}"
    )
    return RedirectResponse(url=install_url, status_code=302)


@router.get("/api/github/callback")
def github_callback(
    installation_id: int, 
    setup_action: str, 
    state: str
) -> RedirectResponse:
    # Added to handle the redirect from GitHub after an app installation is completed.
    # It verifies the state, extracts the workspace ID, and saves the installation_id to Supabase using the Service Role key.
    if setup_action != "install":
        return RedirectResponse(url=f"{frontend_url()}/dashboard?github_connected=0", status_code=302)

    try:
        secret = state_secret()
    except RuntimeError as error:
        raise HTTPException(status_code=500, detail="Server configuration is incomplete") from error

    data = verify_install_state(state, secret)
    workspace_id = data["wid"]

    headers = {
        "Authorization": f"Bearer {supabase_service_role_key()}",
        "apikey": supabase_service_role_key(),
        "Content-Type": "application/json",
        "Prefer": "resolution=merge-duplicates"
    }
    
    payload = {
        "workspace_id": workspace_id,
        "github_installation_id": installation_id
    }
    
    status, _ = _json_post(
        f"{supabase_url()}/rest/v1/github_installations",
        headers,
        payload
    )
    
    if status not in (200, 201, 204):
        # Even if inserting fails (e.g. somehow it already exists), redirect back. 
        # But we could log the error if we had a logger.
        pass

    return RedirectResponse(url=f"{frontend_url()}/dashboard?github_connected=1", status_code=302)
