"""
Purpose:
Defines the shared data contracts and schemas for Engineer 3 Day 2 deliverables.

Architecture Role:
- CheckResult: Standardized telemetry for individual evaluation signals.
- ValidationVerdict: 5-signal composite decision matrix gating Pull Request creation.
- RepairPlan: Self-healing diagnostic and targeted adjustment instructions.
- LoopState & LoopIterationEvent: State machine telemetry and circuit breaker tracking.

Constraints & Invariants:
- Strict boolean conjunction: ValidationVerdict requires 100% of all 5 checks to PASS.
- Max 3 repair attempts: Attempt counter must halt and escalate to NEEDS_HUMAN on 4th attempt.
- Circuit breakers: Enforces cost (<$0.50), timeout (<300s), and cyclic diff prevention.
"""

from __future__ import annotations

import time
from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field


class CheckResult(BaseModel):
    """
    Standardized result for an individual validation signal.
    
    Signals evaluated:
    1. 'requirements': Task scope & requirements satisfied.
    2. 'diff_quality': Diff is minimal, clean, and within size thresholds.
    3. 'repro_test': Standalone reproduction test passes.
    4. 'regression_tests': Existing test suite passes with 0 new failures.
    5. 'security_scan': SAST & secret scanner report 0 new CWE vulnerabilities.
    """
    name: str = Field(..., description="Name of the validation signal")
    passed: bool = Field(..., description="True if check passed; False otherwise")
    score: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence score from 0.0 to 1.0")
    message: str = Field(default="", description="Detailed human-readable evaluation summary")
    details: Dict[str, Any] = Field(default_factory=dict, description="Diagnostics, test counts, or scan metadata")


class ValidationVerdict(BaseModel):
    """
    Composite decision output for Task 34: 5-Signal Validation Engine.
    
    Zero-Override Policy:
    Every check in `checks` must have `passed == True` for `verdict` to be 'PASS'.
    A single failed check immediately transitions `verdict` to 'FAIL' and populates `failure_reasons`.
    """
    verdict: str = Field(..., description="Overall verdict: 'PASS' or 'FAIL'")
    score: float = Field(default=0.0, ge=0.0, le=1.0, description="Normalized composite score across all checks")
    checks: Dict[str, CheckResult] = Field(default_factory=dict, description="Map of signal name to CheckResult")
    failure_reasons: List[str] = Field(default_factory=list, description="Explicit reasons explaining any failures")
    timestamp: str = Field(default_factory=lambda: time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))


class RepairPlan(BaseModel):
    """
    Output model for Task 35: Targeted Repair Agent.
    
    Generated by analyzing failure telemetry from ValidationVerdict.
    Restricts changes strictly to the failing component.
    """
    attempt: int = Field(..., ge=1, le=4, description="Repair iteration attempt number (1-3 allowed; 4 triggers NEEDS_HUMAN)")
    target_components: List[str] = Field(default_factory=list, description="Specific files or functions targeted for repair")
    diagnosis: str = Field(..., description="Root-cause explanation derived from test assertion or scanner failure")
    adjusted_patch: str = Field(default="", description="Corrective code modification or unified diff")
    status: str = Field(default="RETRY", description="Outcome status: 'RETRY' or 'NEEDS_HUMAN'")


class LoopIterationEvent(BaseModel):
    """
    Real-time telemetry event emitted during autonomous repair loop execution.
    Streams to frontend activity feed and evaluation logs.
    """
    iteration: int = Field(..., description="Current iteration round (1, 2, or 3)")
    step: str = Field(..., description="Pipeline step: PLAN, EXECUTE, TEST, VALIDATE, REPAIR")
    status: str = Field(..., description="Step outcome: SUCCESS, FAILURE, SKIPPED, TRIPPED")
    details: Dict[str, Any] = Field(default_factory=dict, description="Step metadata, diff sizes, or failure diagnostics")
    cost: float = Field(default=0.0, description="Incremental API/compute cost incurred in this step")
    timestamp: str = Field(default_factory=lambda: time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))


class LoopState(BaseModel):
    """
    State machine model for Task 36: Full Autonomous Repair Loop.
    
    Tracks loop progression and enforces circuit breakers:
    - Cost Breaker: Cumulative cost must not exceed max_cost ($0.50).
    - Timeout Breaker: Total execution time must not exceed max_time_sec (300s).
    - Cyclic Diff Breaker: Halts if identical diff hash is encountered twice.
    """
    session_id: str = Field(..., description="Unique execution session identifier")
    current_step: str = Field(default="PLAN", description="Current state machine node")
    attempt_count: int = Field(default=0, description="Number of repair iterations executed")
    max_attempts: int = Field(default=3, description="Maximum permitted repair iterations before human escalation")
    
    accumulated_cost: float = Field(default=0.0, description="Total API and compute costs in USD")
    max_cost: float = Field(default=0.50, description="Hard cost ceiling in USD ($0.50)")
    
    elapsed_time_sec: float = Field(default=0.0, description="Total running duration in seconds")
    max_time_sec: float = Field(default=300.0, description="Maximum permitted execution timeout (300 seconds)")
    
    diff_history: List[str] = Field(default_factory=list, description="Historical unified diffs generated across rounds")
    diff_hashes: List[str] = Field(default_factory=list, description="SHA-256 hashes of generated diffs for cycle detection")
    
    circuit_breaker_tripped: bool = Field(default=False, description="True if any circuit breaker threshold was breached")
    trip_reason: Optional[str] = Field(default=None, description="Detailed explanation of the tripped circuit breaker")
    
    events: List[LoopIterationEvent] = Field(default_factory=list, description="Chronological loop telemetry events")
